version: '3'

services:
  shard1Server1:
    container_name: ${SHARD1_SERVER_1_CONTAINER}
    image: mongo
    env_file:
      - .env
    hostname: ${SHARD1_SERVER_1_CONTAINER}
    command: mongod --shardsvr --replSet ${SHARD1_SERVER_REPLICASET_NAME} --port 27017 --dbpath /data/db --keyFile /opt/mongors/keyfile
    ports:
      - 50001:27017
    volumes:
      - /home/shitij/go/src/aapanavyapar-service-viewprovider/sharding/keyfile:/opt/mongors/keyfile
      - ./config_replica.js:/docker-entrypoint-initdb.d/config_replica.js
      - ~/ShardData/${SHARD1_SERVER_1_CONTAINER}:/data/db

  shard1Server2:
    container_name: ${SHARD1_SERVER_2_CONTAINER}
    image: mongo
    env_file:
      - .env
    hostname: ${SHARD1_SERVER_2_CONTAINER}
    command: mongod --shardsvr --replSet ${SHARD1_SERVER_REPLICASET_NAME} --port 27017 --dbpath /data/db --keyFile /opt/mongors/keyfile
    ports:
      - 50002:27017
    volumes:
      - /home/shitij/go/src/aapanavyapar-service-viewprovider/sharding/keyfile:/opt/mongors/keyfile
      - ~/ShardData/${SHARD1_SERVER_2_CONTAINER}:/data/db

  shard1Server3:
    container_name: ${SHARD1_SERVER_3_CONTAINER}
    image: mongo
    env_file:
      - .env
    hostname: ${SHARD1_SERVER_3_CONTAINER}
    command: mongod --shardsvr --replSet ${SHARD1_SERVER_REPLICASET_NAME} --port 27017 --dbpath /data/db --keyFile /opt/mongors/keyfile
    ports:
      - 50003:27017
    volumes:
      - /home/shitij/go/src/aapanavyapar-service-viewprovider/sharding/keyfile:/opt/mongors/keyfile
      - ~/ShardData/${SHARD1_SERVER_3_CONTAINER}:/data/db

volumes:
  shard1Server1: {}
  shard1Server2: {}
  shard1Server3: {}
