version: '3'

services:
  shard2Server1:
    container_name: ${SHARD2_SERVER_1_CONTAINER}
    image: mongo
    env_file:
      - .env
    hostname: ${SHARD2_SERVER_1_CONTAINER}
    command: mongod --shardsvr --replSet ${SHARD2_SERVER_REPLICASET_NAME} --port 27017 --dbpath /data/db --keyFile /opt/mongors/keyfile
    ports:
      - 50004:27017
    volumes:
      - /home/shitij/go/src/aapanavyapar-service-viewprovider/mongo-sharding/keyfile:/opt/mongors/keyfile
      - ./config_replica.js:/docker-entrypoint-initdb.d/config_replica.js
      - ~/ShardData/${SHARD2_SERVER_1_CONTAINER}:/data/db

  shard2Server2:
    container_name: ${SHARD2_SERVER_2_CONTAINER}
    image: mongo
    env_file:
      - .env
    hostname: ${SHARD2_SERVER_2_CONTAINER}
    command: mongod --shardsvr --replSet ${SHARD2_SERVER_REPLICASET_NAME} --port 27017 --dbpath /data/db --keyFile /opt/mongors/keyfile
    ports:
      - 50005:27017
    volumes:
      - /home/shitij/go/src/aapanavyapar-service-viewprovider/mongo-sharding/keyfile:/opt/mongors/keyfile
      - ~/ShardData/${SHARD2_SERVER_2_CONTAINER}:/data/db

  shard2Server3:
    container_name: ${SHARD2_SERVER_3_CONTAINER}
    image: mongo
    env_file:
      - .env
    hostname: ${SHARD2_SERVER_3_CONTAINER}
    command: mongod --shardsvr --replSet ${SHARD2_SERVER_REPLICASET_NAME} --port 27017 --dbpath /data/db --keyFile /opt/mongors/keyfile
    ports:
      - 50006:27017
    volumes:
      - /home/shitij/go/src/aapanavyapar-service-viewprovider/mongo-sharding/keyfile:/opt/mongors/keyfile
      - ~/ShardData/${SHARD2_SERVER_3_CONTAINER}:/data/db

volumes:
  shard2Server1: {}
  shard2Server2: {}
  shard2Server3: {}
