// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0-devel
// 	protoc        v3.13.0
// source: search-message.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetProductsBySearchRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ApiKey  string   `protobuf:"bytes,85,opt,name=apiKey,proto3" json:"apiKey,omitempty"`
	Token   string   `protobuf:"bytes,86,opt,name=token,proto3" json:"token,omitempty"`
	Search  string   `protobuf:"bytes,87,opt,name=search,proto3" json:"search,omitempty"`
	ShopIds []string `protobuf:"bytes,88,rep,name=shopIds,proto3" json:"shopIds,omitempty"`
}

func (x *GetProductsBySearchRequest) Reset() {
	*x = GetProductsBySearchRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_search_message_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetProductsBySearchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProductsBySearchRequest) ProtoMessage() {}

func (x *GetProductsBySearchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_search_message_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProductsBySearchRequest.ProtoReflect.Descriptor instead.
func (*GetProductsBySearchRequest) Descriptor() ([]byte, []int) {
	return file_search_message_proto_rawDescGZIP(), []int{0}
}

func (x *GetProductsBySearchRequest) GetApiKey() string {
	if x != nil {
		return x.ApiKey
	}
	return ""
}

func (x *GetProductsBySearchRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *GetProductsBySearchRequest) GetSearch() string {
	if x != nil {
		return x.Search
	}
	return ""
}

func (x *GetProductsBySearchRequest) GetShopIds() []string {
	if x != nil {
		return x.ShopIds
	}
	return nil
}

type GetProductsBySearchResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Products *ProductsOfShopsNearBy `protobuf:"bytes,89,opt,name=products,proto3" json:"products,omitempty"`
}

func (x *GetProductsBySearchResponse) Reset() {
	*x = GetProductsBySearchResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_search_message_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetProductsBySearchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProductsBySearchResponse) ProtoMessage() {}

func (x *GetProductsBySearchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_search_message_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProductsBySearchResponse.ProtoReflect.Descriptor instead.
func (*GetProductsBySearchResponse) Descriptor() ([]byte, []int) {
	return file_search_message_proto_rawDescGZIP(), []int{1}
}

func (x *GetProductsBySearchResponse) GetProducts() *ProductsOfShopsNearBy {
	if x != nil {
		return x.Products
	}
	return nil
}

type GetShopsBySearchRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ApiKey          string    `protobuf:"bytes,90,opt,name=apiKey,proto3" json:"apiKey,omitempty"`
	Token           string    `protobuf:"bytes,91,opt,name=token,proto3" json:"token,omitempty"`
	Search          string    `protobuf:"bytes,92,opt,name=search,proto3" json:"search,omitempty"`
	DistanceInMeter string    `protobuf:"bytes,93,opt,name=distanceInMeter,proto3" json:"distanceInMeter,omitempty"`
	Location        *Location `protobuf:"bytes,94,opt,name=location,proto3" json:"location,omitempty"`
}

func (x *GetShopsBySearchRequest) Reset() {
	*x = GetShopsBySearchRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_search_message_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetShopsBySearchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetShopsBySearchRequest) ProtoMessage() {}

func (x *GetShopsBySearchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_search_message_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetShopsBySearchRequest.ProtoReflect.Descriptor instead.
func (*GetShopsBySearchRequest) Descriptor() ([]byte, []int) {
	return file_search_message_proto_rawDescGZIP(), []int{2}
}

func (x *GetShopsBySearchRequest) GetApiKey() string {
	if x != nil {
		return x.ApiKey
	}
	return ""
}

func (x *GetShopsBySearchRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *GetShopsBySearchRequest) GetSearch() string {
	if x != nil {
		return x.Search
	}
	return ""
}

func (x *GetShopsBySearchRequest) GetDistanceInMeter() string {
	if x != nil {
		return x.DistanceInMeter
	}
	return ""
}

func (x *GetShopsBySearchRequest) GetLocation() *Location {
	if x != nil {
		return x.Location
	}
	return nil
}

type GetShopsBySearchResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Shops *ShopsNearBy `protobuf:"bytes,95,opt,name=shops,proto3" json:"shops,omitempty"`
}

func (x *GetShopsBySearchResponse) Reset() {
	*x = GetShopsBySearchResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_search_message_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetShopsBySearchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetShopsBySearchResponse) ProtoMessage() {}

func (x *GetShopsBySearchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_search_message_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetShopsBySearchResponse.ProtoReflect.Descriptor instead.
func (*GetShopsBySearchResponse) Descriptor() ([]byte, []int) {
	return file_search_message_proto_rawDescGZIP(), []int{3}
}

func (x *GetShopsBySearchResponse) GetShops() *ShopsNearBy {
	if x != nil {
		return x.Shops
	}
	return nil
}

var File_search_message_proto protoreflect.FileDescriptor

var file_search_message_proto_rawDesc = []byte{
	0x0a, 0x14, 0x73, 0x65, 0x61, 0x72, 0x63, 0x68, 0x2d, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x14, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2d, 0x6d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x7c, 0x0a, 0x1a,
	0x47, 0x65, 0x74, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x73, 0x42, 0x79, 0x53, 0x65, 0x61,
	0x72, 0x63, 0x68, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x61, 0x70,
	0x69, 0x4b, 0x65, 0x79, 0x18, 0x55, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x61, 0x70, 0x69, 0x4b,
	0x65, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x56, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x65, 0x61, 0x72,
	0x63, 0x68, 0x18, 0x57, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x65, 0x61, 0x72, 0x63, 0x68,
	0x12, 0x18, 0x0a, 0x07, 0x73, 0x68, 0x6f, 0x70, 0x49, 0x64, 0x73, 0x18, 0x58, 0x20, 0x03, 0x28,
	0x09, 0x52, 0x07, 0x73, 0x68, 0x6f, 0x70, 0x49, 0x64, 0x73, 0x22, 0x51, 0x0a, 0x1b, 0x47, 0x65,
	0x74, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x73, 0x42, 0x79, 0x53, 0x65, 0x61, 0x72, 0x63,
	0x68, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x32, 0x0a, 0x08, 0x70, 0x72, 0x6f,
	0x64, 0x75, 0x63, 0x74, 0x73, 0x18, 0x59, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x50, 0x72,
	0x6f, 0x64, 0x75, 0x63, 0x74, 0x73, 0x4f, 0x66, 0x53, 0x68, 0x6f, 0x70, 0x73, 0x4e, 0x65, 0x61,
	0x72, 0x42, 0x79, 0x52, 0x08, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x73, 0x22, 0xb0, 0x01,
	0x0a, 0x17, 0x47, 0x65, 0x74, 0x53, 0x68, 0x6f, 0x70, 0x73, 0x42, 0x79, 0x53, 0x65, 0x61, 0x72,
	0x63, 0x68, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x61, 0x70, 0x69,
	0x4b, 0x65, 0x79, 0x18, 0x5a, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x61, 0x70, 0x69, 0x4b, 0x65,
	0x79, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x5b, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x65, 0x61, 0x72, 0x63,
	0x68, 0x18, 0x5c, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x65, 0x61, 0x72, 0x63, 0x68, 0x12,
	0x28, 0x0a, 0x0f, 0x64, 0x69, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x49, 0x6e, 0x4d, 0x65, 0x74,
	0x65, 0x72, 0x18, 0x5d, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0f, 0x64, 0x69, 0x73, 0x74, 0x61, 0x6e,
	0x63, 0x65, 0x49, 0x6e, 0x4d, 0x65, 0x74, 0x65, 0x72, 0x12, 0x25, 0x0a, 0x08, 0x6c, 0x6f, 0x63,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x5e, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x09, 0x2e, 0x4c, 0x6f,
	0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x08, 0x6c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x22, 0x3e, 0x0a, 0x18, 0x47, 0x65, 0x74, 0x53, 0x68, 0x6f, 0x70, 0x73, 0x42, 0x79, 0x53, 0x65,
	0x61, 0x72, 0x63, 0x68, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x22, 0x0a, 0x05,
	0x73, 0x68, 0x6f, 0x70, 0x73, 0x18, 0x5f, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x53, 0x68,
	0x6f, 0x70, 0x73, 0x4e, 0x65, 0x61, 0x72, 0x42, 0x79, 0x52, 0x05, 0x73, 0x68, 0x6f, 0x70, 0x73,
	0x42, 0x30, 0x0a, 0x26, 0x63, 0x6f, 0x6d, 0x2e, 0x61, 0x61, 0x70, 0x61, 0x6e, 0x61, 0x76, 0x79,
	0x61, 0x70, 0x61, 0x72, 0x2e, 0x61, 0x61, 0x70, 0x61, 0x6e, 0x61, 0x76, 0x79, 0x61, 0x70, 0x61,
	0x72, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x50, 0x01, 0x5a, 0x04, 0x2e, 0x3b,
	0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_search_message_proto_rawDescOnce sync.Once
	file_search_message_proto_rawDescData = file_search_message_proto_rawDesc
)

func file_search_message_proto_rawDescGZIP() []byte {
	file_search_message_proto_rawDescOnce.Do(func() {
		file_search_message_proto_rawDescData = protoimpl.X.CompressGZIP(file_search_message_proto_rawDescData)
	})
	return file_search_message_proto_rawDescData
}

var file_search_message_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_search_message_proto_goTypes = []interface{}{
	(*GetProductsBySearchRequest)(nil),  // 0: GetProductsBySearchRequest
	(*GetProductsBySearchResponse)(nil), // 1: GetProductsBySearchResponse
	(*GetShopsBySearchRequest)(nil),     // 2: GetShopsBySearchRequest
	(*GetShopsBySearchResponse)(nil),    // 3: GetShopsBySearchResponse
	(*ProductsOfShopsNearBy)(nil),       // 4: ProductsOfShopsNearBy
	(*Location)(nil),                    // 5: Location
	(*ShopsNearBy)(nil),                 // 6: ShopsNearBy
}
var file_search_message_proto_depIdxs = []int32{
	4, // 0: GetProductsBySearchResponse.products:type_name -> ProductsOfShopsNearBy
	5, // 1: GetShopsBySearchRequest.location:type_name -> Location
	6, // 2: GetShopsBySearchResponse.shops:type_name -> ShopsNearBy
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_search_message_proto_init() }
func file_search_message_proto_init() {
	if File_search_message_proto != nil {
		return
	}
	file_common_message_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_search_message_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetProductsBySearchRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_search_message_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetProductsBySearchResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_search_message_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetShopsBySearchRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_search_message_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetShopsBySearchResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_search_message_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_search_message_proto_goTypes,
		DependencyIndexes: file_search_message_proto_depIdxs,
		MessageInfos:      file_search_message_proto_msgTypes,
	}.Build()
	File_search_message_proto = out.File
	file_search_message_proto_rawDesc = nil
	file_search_message_proto_goTypes = nil
	file_search_message_proto_depIdxs = nil
}
