// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0-devel
// 	protoc        v3.13.0
// source: trending-message.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Location struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Longitude string `protobuf:"bytes,9,opt,name=Longitude,proto3" json:"Longitude,omitempty"`
	Latitude  string `protobuf:"bytes,10,opt,name=Latitude,proto3" json:"Latitude,omitempty"`
}

func (x *Location) Reset() {
	*x = Location{}
	if protoimpl.UnsafeEnabled {
		mi := &file_trending_message_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Location) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Location) ProtoMessage() {}

func (x *Location) ProtoReflect() protoreflect.Message {
	mi := &file_trending_message_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Location.ProtoReflect.Descriptor instead.
func (*Location) Descriptor() ([]byte, []int) {
	return file_trending_message_proto_rawDescGZIP(), []int{0}
}

func (x *Location) GetLongitude() string {
	if x != nil {
		return x.Longitude
	}
	return ""
}

func (x *Location) GetLatitude() string {
	if x != nil {
		return x.Latitude
	}
	return ""
}

type TrendingData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SubCategory      string `protobuf:"bytes,11,opt,name=subCategory,proto3" json:"subCategory,omitempty"`
	ProductImage     string `protobuf:"bytes,12,opt,name=productImage,proto3" json:"productImage,omitempty"`
	ProductName      string `protobuf:"bytes,13,opt,name=productName,proto3" json:"productName,omitempty"`
	ShopName         string `protobuf:"bytes,14,opt,name=shopName,proto3" json:"shopName,omitempty"`
	ShortDescription string `protobuf:"bytes,15,opt,name=shortDescription,proto3" json:"shortDescription,omitempty"`
	ShopRating       string `protobuf:"bytes,16,opt,name=shopRating,proto3" json:"shopRating,omitempty"`
	ProductLikes     int64  `protobuf:"varint,17,opt,name=productLikes,proto3" json:"productLikes,omitempty"`
}

func (x *TrendingData) Reset() {
	*x = TrendingData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_trending_message_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TrendingData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrendingData) ProtoMessage() {}

func (x *TrendingData) ProtoReflect() protoreflect.Message {
	mi := &file_trending_message_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrendingData.ProtoReflect.Descriptor instead.
func (*TrendingData) Descriptor() ([]byte, []int) {
	return file_trending_message_proto_rawDescGZIP(), []int{1}
}

func (x *TrendingData) GetSubCategory() string {
	if x != nil {
		return x.SubCategory
	}
	return ""
}

func (x *TrendingData) GetProductImage() string {
	if x != nil {
		return x.ProductImage
	}
	return ""
}

func (x *TrendingData) GetProductName() string {
	if x != nil {
		return x.ProductName
	}
	return ""
}

func (x *TrendingData) GetShopName() string {
	if x != nil {
		return x.ShopName
	}
	return ""
}

func (x *TrendingData) GetShortDescription() string {
	if x != nil {
		return x.ShortDescription
	}
	return ""
}

func (x *TrendingData) GetShopRating() string {
	if x != nil {
		return x.ShopRating
	}
	return ""
}

func (x *TrendingData) GetProductLikes() int64 {
	if x != nil {
		return x.ProductLikes
	}
	return 0
}

type GetTrendingCategoriesRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ApiKey string `protobuf:"bytes,1,opt,name=apiKey,proto3" json:"apiKey,omitempty"`
	Token  string `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
}

func (x *GetTrendingCategoriesRequest) Reset() {
	*x = GetTrendingCategoriesRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_trending_message_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetTrendingCategoriesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTrendingCategoriesRequest) ProtoMessage() {}

func (x *GetTrendingCategoriesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_trending_message_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTrendingCategoriesRequest.ProtoReflect.Descriptor instead.
func (*GetTrendingCategoriesRequest) Descriptor() ([]byte, []int) {
	return file_trending_message_proto_rawDescGZIP(), []int{2}
}

func (x *GetTrendingCategoriesRequest) GetApiKey() string {
	if x != nil {
		return x.ApiKey
	}
	return ""
}

func (x *GetTrendingCategoriesRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type GetTrendingCategoriesResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CategoryData []string `protobuf:"bytes,3,rep,name=categoryData,proto3" json:"categoryData,omitempty"`
}

func (x *GetTrendingCategoriesResponse) Reset() {
	*x = GetTrendingCategoriesResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_trending_message_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetTrendingCategoriesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTrendingCategoriesResponse) ProtoMessage() {}

func (x *GetTrendingCategoriesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_trending_message_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTrendingCategoriesResponse.ProtoReflect.Descriptor instead.
func (*GetTrendingCategoriesResponse) Descriptor() ([]byte, []int) {
	return file_trending_message_proto_rawDescGZIP(), []int{3}
}

func (x *GetTrendingCategoriesResponse) GetCategoryData() []string {
	if x != nil {
		return x.CategoryData
	}
	return nil
}

type GetTrendingDataByCategoriesRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ApiKey     string    `protobuf:"bytes,4,opt,name=apiKey,proto3" json:"apiKey,omitempty"`
	Token      string    `protobuf:"bytes,5,opt,name=token,proto3" json:"token,omitempty"`
	CategoryId uint32    `protobuf:"varint,6,opt,name=categoryId,proto3" json:"categoryId,omitempty"`
	Location   *Location `protobuf:"bytes,7,opt,name=location,proto3" json:"location,omitempty"`
}

func (x *GetTrendingDataByCategoriesRequest) Reset() {
	*x = GetTrendingDataByCategoriesRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_trending_message_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetTrendingDataByCategoriesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTrendingDataByCategoriesRequest) ProtoMessage() {}

func (x *GetTrendingDataByCategoriesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_trending_message_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTrendingDataByCategoriesRequest.ProtoReflect.Descriptor instead.
func (*GetTrendingDataByCategoriesRequest) Descriptor() ([]byte, []int) {
	return file_trending_message_proto_rawDescGZIP(), []int{4}
}

func (x *GetTrendingDataByCategoriesRequest) GetApiKey() string {
	if x != nil {
		return x.ApiKey
	}
	return ""
}

func (x *GetTrendingDataByCategoriesRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *GetTrendingDataByCategoriesRequest) GetCategoryId() uint32 {
	if x != nil {
		return x.CategoryId
	}
	return 0
}

func (x *GetTrendingDataByCategoriesRequest) GetLocation() *Location {
	if x != nil {
		return x.Location
	}
	return nil
}

type GetTrendingDataByCategoriesResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TrendingData *TrendingData `protobuf:"bytes,8,opt,name=trendingData,proto3" json:"trendingData,omitempty"`
}

func (x *GetTrendingDataByCategoriesResponse) Reset() {
	*x = GetTrendingDataByCategoriesResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_trending_message_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetTrendingDataByCategoriesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTrendingDataByCategoriesResponse) ProtoMessage() {}

func (x *GetTrendingDataByCategoriesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_trending_message_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTrendingDataByCategoriesResponse.ProtoReflect.Descriptor instead.
func (*GetTrendingDataByCategoriesResponse) Descriptor() ([]byte, []int) {
	return file_trending_message_proto_rawDescGZIP(), []int{5}
}

func (x *GetTrendingDataByCategoriesResponse) GetTrendingData() *TrendingData {
	if x != nil {
		return x.TrendingData
	}
	return nil
}

var File_trending_message_proto protoreflect.FileDescriptor

var file_trending_message_proto_rawDesc = []byte{
	0x0a, 0x16, 0x74, 0x72, 0x65, 0x6e, 0x64, 0x69, 0x6e, 0x67, 0x2d, 0x6d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x44, 0x0a, 0x08, 0x4c, 0x6f, 0x63, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x12, 0x1c, 0x0a, 0x09, 0x4c, 0x6f, 0x6e, 0x67, 0x69, 0x74, 0x75, 0x64,
	0x65, 0x18, 0x09, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x4c, 0x6f, 0x6e, 0x67, 0x69, 0x74, 0x75,
	0x64, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x4c, 0x61, 0x74, 0x69, 0x74, 0x75, 0x64, 0x65, 0x18, 0x0a,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x4c, 0x61, 0x74, 0x69, 0x74, 0x75, 0x64, 0x65, 0x22, 0x82,
	0x02, 0x0a, 0x0c, 0x54, 0x72, 0x65, 0x6e, 0x64, 0x69, 0x6e, 0x67, 0x44, 0x61, 0x74, 0x61, 0x12,
	0x20, 0x0a, 0x0b, 0x73, 0x75, 0x62, 0x43, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x18, 0x0b,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x73, 0x75, 0x62, 0x43, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72,
	0x79, 0x12, 0x22, 0x0a, 0x0c, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x49, 0x6d, 0x61, 0x67,
	0x65, 0x18, 0x0c, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74,
	0x49, 0x6d, 0x61, 0x67, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74,
	0x4e, 0x61, 0x6d, 0x65, 0x18, 0x0d, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x70, 0x72, 0x6f, 0x64,
	0x75, 0x63, 0x74, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x73, 0x68, 0x6f, 0x70, 0x4e,
	0x61, 0x6d, 0x65, 0x18, 0x0e, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x73, 0x68, 0x6f, 0x70, 0x4e,
	0x61, 0x6d, 0x65, 0x12, 0x2a, 0x0a, 0x10, 0x73, 0x68, 0x6f, 0x72, 0x74, 0x44, 0x65, 0x73, 0x63,
	0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x0f, 0x20, 0x01, 0x28, 0x09, 0x52, 0x10, 0x73,
	0x68, 0x6f, 0x72, 0x74, 0x44, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x12,
	0x1e, 0x0a, 0x0a, 0x73, 0x68, 0x6f, 0x70, 0x52, 0x61, 0x74, 0x69, 0x6e, 0x67, 0x18, 0x10, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x0a, 0x73, 0x68, 0x6f, 0x70, 0x52, 0x61, 0x74, 0x69, 0x6e, 0x67, 0x12,
	0x22, 0x0a, 0x0c, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x4c, 0x69, 0x6b, 0x65, 0x73, 0x18,
	0x11, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0c, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x4c, 0x69,
	0x6b, 0x65, 0x73, 0x22, 0x4c, 0x0a, 0x1c, 0x47, 0x65, 0x74, 0x54, 0x72, 0x65, 0x6e, 0x64, 0x69,
	0x6e, 0x67, 0x43, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x69, 0x65, 0x73, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x61, 0x70, 0x69, 0x4b, 0x65, 0x79, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x06, 0x61, 0x70, 0x69, 0x4b, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x74,
	0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x6f, 0x6b, 0x65,
	0x6e, 0x22, 0x43, 0x0a, 0x1d, 0x47, 0x65, 0x74, 0x54, 0x72, 0x65, 0x6e, 0x64, 0x69, 0x6e, 0x67,
	0x43, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x69, 0x65, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x22, 0x0a, 0x0c, 0x63, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x44, 0x61,
	0x74, 0x61, 0x18, 0x03, 0x20, 0x03, 0x28, 0x09, 0x52, 0x0c, 0x63, 0x61, 0x74, 0x65, 0x67, 0x6f,
	0x72, 0x79, 0x44, 0x61, 0x74, 0x61, 0x22, 0x99, 0x01, 0x0a, 0x22, 0x47, 0x65, 0x74, 0x54, 0x72,
	0x65, 0x6e, 0x64, 0x69, 0x6e, 0x67, 0x44, 0x61, 0x74, 0x61, 0x42, 0x79, 0x43, 0x61, 0x74, 0x65,
	0x67, 0x6f, 0x72, 0x69, 0x65, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x16, 0x0a,
	0x06, 0x61, 0x70, 0x69, 0x4b, 0x65, 0x79, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x61,
	0x70, 0x69, 0x4b, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x05,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x12, 0x1e, 0x0a, 0x0a, 0x63,
	0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x49, 0x64, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0d, 0x52,
	0x0a, 0x63, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x49, 0x64, 0x12, 0x25, 0x0a, 0x08, 0x6c,
	0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x07, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x09, 0x2e,
	0x4c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x08, 0x6c, 0x6f, 0x63, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x22, 0x58, 0x0a, 0x23, 0x47, 0x65, 0x74, 0x54, 0x72, 0x65, 0x6e, 0x64, 0x69, 0x6e,
	0x67, 0x44, 0x61, 0x74, 0x61, 0x42, 0x79, 0x43, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x69, 0x65,
	0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x31, 0x0a, 0x0c, 0x74, 0x72, 0x65,
	0x6e, 0x64, 0x69, 0x6e, 0x67, 0x44, 0x61, 0x74, 0x61, 0x18, 0x08, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x0d, 0x2e, 0x54, 0x72, 0x65, 0x6e, 0x64, 0x69, 0x6e, 0x67, 0x44, 0x61, 0x74, 0x61, 0x52, 0x0c,
	0x74, 0x72, 0x65, 0x6e, 0x64, 0x69, 0x6e, 0x67, 0x44, 0x61, 0x74, 0x61, 0x42, 0x30, 0x0a, 0x26,
	0x63, 0x6f, 0x6d, 0x2e, 0x61, 0x61, 0x70, 0x61, 0x6e, 0x61, 0x76, 0x79, 0x61, 0x70, 0x61, 0x72,
	0x2e, 0x61, 0x61, 0x70, 0x61, 0x6e, 0x61, 0x76, 0x79, 0x61, 0x70, 0x61, 0x72, 0x2e, 0x73, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x50, 0x01, 0x5a, 0x04, 0x2e, 0x3b, 0x70, 0x62, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_trending_message_proto_rawDescOnce sync.Once
	file_trending_message_proto_rawDescData = file_trending_message_proto_rawDesc
)

func file_trending_message_proto_rawDescGZIP() []byte {
	file_trending_message_proto_rawDescOnce.Do(func() {
		file_trending_message_proto_rawDescData = protoimpl.X.CompressGZIP(file_trending_message_proto_rawDescData)
	})
	return file_trending_message_proto_rawDescData
}

var file_trending_message_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_trending_message_proto_goTypes = []interface{}{
	(*Location)(nil),                            // 0: Location
	(*TrendingData)(nil),                        // 1: TrendingData
	(*GetTrendingCategoriesRequest)(nil),        // 2: GetTrendingCategoriesRequest
	(*GetTrendingCategoriesResponse)(nil),       // 3: GetTrendingCategoriesResponse
	(*GetTrendingDataByCategoriesRequest)(nil),  // 4: GetTrendingDataByCategoriesRequest
	(*GetTrendingDataByCategoriesResponse)(nil), // 5: GetTrendingDataByCategoriesResponse
}
var file_trending_message_proto_depIdxs = []int32{
	0, // 0: GetTrendingDataByCategoriesRequest.location:type_name -> Location
	1, // 1: GetTrendingDataByCategoriesResponse.trendingData:type_name -> TrendingData
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_trending_message_proto_init() }
func file_trending_message_proto_init() {
	if File_trending_message_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_trending_message_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Location); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_trending_message_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TrendingData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_trending_message_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetTrendingCategoriesRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_trending_message_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetTrendingCategoriesResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_trending_message_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetTrendingDataByCategoriesRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_trending_message_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetTrendingDataByCategoriesResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_trending_message_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_trending_message_proto_goTypes,
		DependencyIndexes: file_trending_message_proto_depIdxs,
		MessageInfos:      file_trending_message_proto_msgTypes,
	}.Build()
	File_trending_message_proto = out.File
	file_trending_message_proto_rawDesc = nil
	file_trending_message_proto_goTypes = nil
	file_trending_message_proto_depIdxs = nil
}
