// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0-devel
// 	protoc        v3.13.0
// source: user-commands-message.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AddToLikeProductRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Token     string `protobuf:"bytes,25,opt,name=token,proto3" json:"token,omitempty"`
	ApiKey    string `protobuf:"bytes,26,opt,name=apiKey,proto3" json:"apiKey,omitempty"`
	ProductId string `protobuf:"bytes,27,opt,name=productId,proto3" json:"productId,omitempty"`
}

func (x *AddToLikeProductRequest) Reset() {
	*x = AddToLikeProductRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_user_commands_message_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddToLikeProductRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddToLikeProductRequest) ProtoMessage() {}

func (x *AddToLikeProductRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_commands_message_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddToLikeProductRequest.ProtoReflect.Descriptor instead.
func (*AddToLikeProductRequest) Descriptor() ([]byte, []int) {
	return file_user_commands_message_proto_rawDescGZIP(), []int{0}
}

func (x *AddToLikeProductRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *AddToLikeProductRequest) GetApiKey() string {
	if x != nil {
		return x.ApiKey
	}
	return ""
}

func (x *AddToLikeProductRequest) GetProductId() string {
	if x != nil {
		return x.ProductId
	}
	return ""
}

type AddToLikeProductResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status bool `protobuf:"varint,28,opt,name=status,proto3" json:"status,omitempty"`
}

func (x *AddToLikeProductResponse) Reset() {
	*x = AddToLikeProductResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_user_commands_message_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddToLikeProductResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddToLikeProductResponse) ProtoMessage() {}

func (x *AddToLikeProductResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_commands_message_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddToLikeProductResponse.ProtoReflect.Descriptor instead.
func (*AddToLikeProductResponse) Descriptor() ([]byte, []int) {
	return file_user_commands_message_proto_rawDescGZIP(), []int{1}
}

func (x *AddToLikeProductResponse) GetStatus() bool {
	if x != nil {
		return x.Status
	}
	return false
}

type RemoveFromLikeProductRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Token     string `protobuf:"bytes,29,opt,name=token,proto3" json:"token,omitempty"`
	ApiKey    string `protobuf:"bytes,30,opt,name=apiKey,proto3" json:"apiKey,omitempty"`
	ProductId string `protobuf:"bytes,31,opt,name=productId,proto3" json:"productId,omitempty"`
}

func (x *RemoveFromLikeProductRequest) Reset() {
	*x = RemoveFromLikeProductRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_user_commands_message_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RemoveFromLikeProductRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveFromLikeProductRequest) ProtoMessage() {}

func (x *RemoveFromLikeProductRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_commands_message_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveFromLikeProductRequest.ProtoReflect.Descriptor instead.
func (*RemoveFromLikeProductRequest) Descriptor() ([]byte, []int) {
	return file_user_commands_message_proto_rawDescGZIP(), []int{2}
}

func (x *RemoveFromLikeProductRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *RemoveFromLikeProductRequest) GetApiKey() string {
	if x != nil {
		return x.ApiKey
	}
	return ""
}

func (x *RemoveFromLikeProductRequest) GetProductId() string {
	if x != nil {
		return x.ProductId
	}
	return ""
}

type RemoveFromLikeProductResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status bool `protobuf:"varint,32,opt,name=status,proto3" json:"status,omitempty"`
}

func (x *RemoveFromLikeProductResponse) Reset() {
	*x = RemoveFromLikeProductResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_user_commands_message_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RemoveFromLikeProductResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveFromLikeProductResponse) ProtoMessage() {}

func (x *RemoveFromLikeProductResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_commands_message_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveFromLikeProductResponse.ProtoReflect.Descriptor instead.
func (*RemoveFromLikeProductResponse) Descriptor() ([]byte, []int) {
	return file_user_commands_message_proto_rawDescGZIP(), []int{3}
}

func (x *RemoveFromLikeProductResponse) GetStatus() bool {
	if x != nil {
		return x.Status
	}
	return false
}

type AddToCartProductRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Token     string `protobuf:"bytes,33,opt,name=token,proto3" json:"token,omitempty"`
	ApiKey    string `protobuf:"bytes,34,opt,name=apiKey,proto3" json:"apiKey,omitempty"`
	ProductId string `protobuf:"bytes,35,opt,name=productId,proto3" json:"productId,omitempty"`
}

func (x *AddToCartProductRequest) Reset() {
	*x = AddToCartProductRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_user_commands_message_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddToCartProductRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddToCartProductRequest) ProtoMessage() {}

func (x *AddToCartProductRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_commands_message_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddToCartProductRequest.ProtoReflect.Descriptor instead.
func (*AddToCartProductRequest) Descriptor() ([]byte, []int) {
	return file_user_commands_message_proto_rawDescGZIP(), []int{4}
}

func (x *AddToCartProductRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *AddToCartProductRequest) GetApiKey() string {
	if x != nil {
		return x.ApiKey
	}
	return ""
}

func (x *AddToCartProductRequest) GetProductId() string {
	if x != nil {
		return x.ProductId
	}
	return ""
}

type AddToCartProductResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status bool `protobuf:"varint,36,opt,name=status,proto3" json:"status,omitempty"`
}

func (x *AddToCartProductResponse) Reset() {
	*x = AddToCartProductResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_user_commands_message_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddToCartProductResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddToCartProductResponse) ProtoMessage() {}

func (x *AddToCartProductResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_commands_message_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddToCartProductResponse.ProtoReflect.Descriptor instead.
func (*AddToCartProductResponse) Descriptor() ([]byte, []int) {
	return file_user_commands_message_proto_rawDescGZIP(), []int{5}
}

func (x *AddToCartProductResponse) GetStatus() bool {
	if x != nil {
		return x.Status
	}
	return false
}

type RemoveFromCartProductRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Token     string `protobuf:"bytes,37,opt,name=token,proto3" json:"token,omitempty"`
	ApiKey    string `protobuf:"bytes,38,opt,name=apiKey,proto3" json:"apiKey,omitempty"`
	ProductId string `protobuf:"bytes,39,opt,name=productId,proto3" json:"productId,omitempty"`
}

func (x *RemoveFromCartProductRequest) Reset() {
	*x = RemoveFromCartProductRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_user_commands_message_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RemoveFromCartProductRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveFromCartProductRequest) ProtoMessage() {}

func (x *RemoveFromCartProductRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_commands_message_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveFromCartProductRequest.ProtoReflect.Descriptor instead.
func (*RemoveFromCartProductRequest) Descriptor() ([]byte, []int) {
	return file_user_commands_message_proto_rawDescGZIP(), []int{6}
}

func (x *RemoveFromCartProductRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *RemoveFromCartProductRequest) GetApiKey() string {
	if x != nil {
		return x.ApiKey
	}
	return ""
}

func (x *RemoveFromCartProductRequest) GetProductId() string {
	if x != nil {
		return x.ProductId
	}
	return ""
}

type RemoveFromCartProductResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status bool `protobuf:"varint,40,opt,name=status,proto3" json:"status,omitempty"`
}

func (x *RemoveFromCartProductResponse) Reset() {
	*x = RemoveFromCartProductResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_user_commands_message_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RemoveFromCartProductResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveFromCartProductResponse) ProtoMessage() {}

func (x *RemoveFromCartProductResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_commands_message_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveFromCartProductResponse.ProtoReflect.Descriptor instead.
func (*RemoveFromCartProductResponse) Descriptor() ([]byte, []int) {
	return file_user_commands_message_proto_rawDescGZIP(), []int{7}
}

func (x *RemoveFromCartProductResponse) GetStatus() bool {
	if x != nil {
		return x.Status
	}
	return false
}

var File_user_commands_message_proto protoreflect.FileDescriptor

var file_user_commands_message_proto_rawDesc = []byte{
	0x0a, 0x1b, 0x75, 0x73, 0x65, 0x72, 0x2d, 0x63, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x73, 0x2d,
	0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x65, 0x0a,
	0x17, 0x41, 0x64, 0x64, 0x54, 0x6f, 0x4c, 0x69, 0x6b, 0x65, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x63,
	0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x6b, 0x65,
	0x6e, 0x18, 0x19, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x12, 0x16,
	0x0a, 0x06, 0x61, 0x70, 0x69, 0x4b, 0x65, 0x79, 0x18, 0x1a, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06,
	0x61, 0x70, 0x69, 0x4b, 0x65, 0x79, 0x12, 0x1c, 0x0a, 0x09, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63,
	0x74, 0x49, 0x64, 0x18, 0x1b, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x70, 0x72, 0x6f, 0x64, 0x75,
	0x63, 0x74, 0x49, 0x64, 0x22, 0x32, 0x0a, 0x18, 0x41, 0x64, 0x64, 0x54, 0x6f, 0x4c, 0x69, 0x6b,
	0x65, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x1c, 0x20, 0x01, 0x28, 0x08,
	0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x22, 0x6a, 0x0a, 0x1c, 0x52, 0x65, 0x6d, 0x6f,
	0x76, 0x65, 0x46, 0x72, 0x6f, 0x6d, 0x4c, 0x69, 0x6b, 0x65, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x63,
	0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x6b, 0x65,
	0x6e, 0x18, 0x1d, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x12, 0x16,
	0x0a, 0x06, 0x61, 0x70, 0x69, 0x4b, 0x65, 0x79, 0x18, 0x1e, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06,
	0x61, 0x70, 0x69, 0x4b, 0x65, 0x79, 0x12, 0x1c, 0x0a, 0x09, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63,
	0x74, 0x49, 0x64, 0x18, 0x1f, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x70, 0x72, 0x6f, 0x64, 0x75,
	0x63, 0x74, 0x49, 0x64, 0x22, 0x37, 0x0a, 0x1d, 0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x46, 0x72,
	0x6f, 0x6d, 0x4c, 0x69, 0x6b, 0x65, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18,
	0x20, 0x20, 0x01, 0x28, 0x08, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x22, 0x65, 0x0a,
	0x17, 0x41, 0x64, 0x64, 0x54, 0x6f, 0x43, 0x61, 0x72, 0x74, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x63,
	0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x6b, 0x65,
	0x6e, 0x18, 0x21, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x12, 0x16,
	0x0a, 0x06, 0x61, 0x70, 0x69, 0x4b, 0x65, 0x79, 0x18, 0x22, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06,
	0x61, 0x70, 0x69, 0x4b, 0x65, 0x79, 0x12, 0x1c, 0x0a, 0x09, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63,
	0x74, 0x49, 0x64, 0x18, 0x23, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x70, 0x72, 0x6f, 0x64, 0x75,
	0x63, 0x74, 0x49, 0x64, 0x22, 0x32, 0x0a, 0x18, 0x41, 0x64, 0x64, 0x54, 0x6f, 0x43, 0x61, 0x72,
	0x74, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x24, 0x20, 0x01, 0x28, 0x08,
	0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x22, 0x6a, 0x0a, 0x1c, 0x52, 0x65, 0x6d, 0x6f,
	0x76, 0x65, 0x46, 0x72, 0x6f, 0x6d, 0x43, 0x61, 0x72, 0x74, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x63,
	0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x6b, 0x65,
	0x6e, 0x18, 0x25, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x12, 0x16,
	0x0a, 0x06, 0x61, 0x70, 0x69, 0x4b, 0x65, 0x79, 0x18, 0x26, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06,
	0x61, 0x70, 0x69, 0x4b, 0x65, 0x79, 0x12, 0x1c, 0x0a, 0x09, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63,
	0x74, 0x49, 0x64, 0x18, 0x27, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x70, 0x72, 0x6f, 0x64, 0x75,
	0x63, 0x74, 0x49, 0x64, 0x22, 0x37, 0x0a, 0x1d, 0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x46, 0x72,
	0x6f, 0x6d, 0x43, 0x61, 0x72, 0x74, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18,
	0x28, 0x20, 0x01, 0x28, 0x08, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x42, 0x30, 0x0a,
	0x26, 0x63, 0x6f, 0x6d, 0x2e, 0x61, 0x61, 0x70, 0x61, 0x6e, 0x61, 0x76, 0x79, 0x61, 0x70, 0x61,
	0x72, 0x2e, 0x61, 0x61, 0x70, 0x61, 0x6e, 0x61, 0x76, 0x79, 0x61, 0x70, 0x61, 0x72, 0x2e, 0x73,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x50, 0x01, 0x5a, 0x04, 0x2e, 0x3b, 0x70, 0x62, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_user_commands_message_proto_rawDescOnce sync.Once
	file_user_commands_message_proto_rawDescData = file_user_commands_message_proto_rawDesc
)

func file_user_commands_message_proto_rawDescGZIP() []byte {
	file_user_commands_message_proto_rawDescOnce.Do(func() {
		file_user_commands_message_proto_rawDescData = protoimpl.X.CompressGZIP(file_user_commands_message_proto_rawDescData)
	})
	return file_user_commands_message_proto_rawDescData
}

var file_user_commands_message_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_user_commands_message_proto_goTypes = []interface{}{
	(*AddToLikeProductRequest)(nil),       // 0: AddToLikeProductRequest
	(*AddToLikeProductResponse)(nil),      // 1: AddToLikeProductResponse
	(*RemoveFromLikeProductRequest)(nil),  // 2: RemoveFromLikeProductRequest
	(*RemoveFromLikeProductResponse)(nil), // 3: RemoveFromLikeProductResponse
	(*AddToCartProductRequest)(nil),       // 4: AddToCartProductRequest
	(*AddToCartProductResponse)(nil),      // 5: AddToCartProductResponse
	(*RemoveFromCartProductRequest)(nil),  // 6: RemoveFromCartProductRequest
	(*RemoveFromCartProductResponse)(nil), // 7: RemoveFromCartProductResponse
}
var file_user_commands_message_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_user_commands_message_proto_init() }
func file_user_commands_message_proto_init() {
	if File_user_commands_message_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_user_commands_message_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddToLikeProductRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_user_commands_message_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddToLikeProductResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_user_commands_message_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RemoveFromLikeProductRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_user_commands_message_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RemoveFromLikeProductResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_user_commands_message_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddToCartProductRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_user_commands_message_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddToCartProductResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_user_commands_message_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RemoveFromCartProductRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_user_commands_message_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RemoveFromCartProductResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_user_commands_message_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_user_commands_message_proto_goTypes,
		DependencyIndexes: file_user_commands_message_proto_depIdxs,
		MessageInfos:      file_user_commands_message_proto_msgTypes,
	}.Build()
	File_user_commands_message_proto = out.File
	file_user_commands_message_proto_rawDesc = nil
	file_user_commands_message_proto_goTypes = nil
	file_user_commands_message_proto_depIdxs = nil
}
